// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Ahorcado;

/************************************************************/
/**
 * 
 */
class Partida {
	/**
	 * 
	 */
	public String palabra;
	/**
	 * 
	 */
	public char[] letras;
	/**
	 * 
	 */
	public String pista;
	/**
	 * 
	 */
	public int intentos;
	/**
	 * Funciona para saber si la partida ha terminado o no.
	 */
	public boolean fin;

	/**
	 * 
	 */
	public void generaPalabra() {
	}

	/**
	 * 
	 */
	public void generaPista() {
	}

	/**
	 * 
	 */
	public void verificarLetra() {
	}

	/**
	 * 
	 */
	public void verificarFin() {
	}
};
